### ISSUE TITLE
The `county` and `city` variables in the "zipcode.ts" file are written in reverse.

### ISSUE THREAD

**Issue by erik1110** [hexschool/freyja#2]
如標題說明，參數名稱命名錯誤
county 是縣市
city 是城市

const ZipCodeMap = [
    { detail: '100臺北市中正區', zipcode: 100, county: '臺北市', city: '中正區' },
    { detail: '103臺北市大同區', zipcode: 103, county: '臺北市', city: '大同區' },
    { detail: '104臺北市中山區', zipcode: 104, county: '臺北市', city: '中山區' }
    ...
]

**Comment by kimnTai** [comment]
您好，該檔案資料來源為 twzipcode-data 套件，
https://www.npmjs.com/package/twzipcode-data

是希望改成

```
{ detail: '100臺北市中正區', zipcode: 100, city: '臺北市', county: '中正區' },
```

的格式嗎

**Comment by erik1110** [comment]
嗨您好，原來原始資料命名就反了XDD
由於要改太多了，建議可以直接程式改最快
`ZipCodeMap.forEach(item => {
    [item.county, item.city] = [item.city, item.county];
});`
