### ISSUE TITLE
房型管理缺少房間格局分類

### ISSUE THREAD

**Issue by Nighthree** [hexschool/freyja#5]
如題，
看文檔理解為 facilityInfo 對應"房內設備"、amenityInfo 對應"備品提供"
缺少"房間格局"的對應分類

![2024-01-15 160254](https://github.com/hexschool/freyja/assets/48798616/0f00df3d-9b6b-4528-9726-bcae1991c670)
![2024-01-15 160313](https://github.com/hexschool/freyja/assets/48798616/5576388b-fbf5-42cc-b88e-1b2df08bbd8a)

**Comment by kimnTai** [comment]
好的，我確認一下
